
pipeline {
  agent any

  stages {
   
    stage('build image'){
        steps{
            
            sh 'docker login $ACR_LOGIN -u $ACR_USERNAME -p $ACR_PASSWORD'
            sh 'docker build tage $ACR_LOGIN/fasobestapp .'
        
     }
    }
    stage('pushing image'){
        steps{   
            sh 'docker push $ACR_LOGIN/fasobestapp'  
     } 
   
  }
 stage('run image'){
        steps{   
            sh 'docker run -it -p 3000:4200 $ACR_LOGIN/fasobestapp'  
     } 
   
  }
  
}
}